config/routes.rb
Rails.application.routes.draw do


	get '/about' => 'pages#about'
	get '/freelance' => 'pages#freelance'
  get '/projects' => 'pages#projects'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resource :session
  resources :jobs
  resources :users do
  	resources :jobs, only: [:new, :create]
  end

  root "jobs#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/job.rb
class Job < ActiveRecord::Base

	validates :title, presence: true
	validates :company, presence: true
	validates :company_url, presence: true
	validates :description, presence: true, length: {minimum: 10}
	validates :how_to_apply, presence: true
	validates :salary, presence: true
	validates :area_of_london, presence: true

	belongs_to :user

	scope :published, -> { where(approved: true) }
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password_confirmation, presence: true

	has_many :jobs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end
  end

  def logged_in?
  	session[:user_id].present?
  end

  def require_user
  	unless logged_in?
  		flash[:error] = "You need to be logged in"
  		redirect_to new_session_path
  	end
  end

  def current_user_owns_job
  	job = Job.find(params[:id])
  	unless logged_in? and current_user == job.user
  		flash[:error] = "Only the owner can edit"
  		redirect_to job_path(job)
  	end
  end


  helper_method :current_user
  helper_method :logged_in?
  helper_method :require_user

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.order(created_at: :desc).published
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    require_user
  	@user = User.find(params[:user_id])
    @job = @user.jobs.new
  end

  def create
    require_user
    @user = User.find(params[:user_id])
    @job = @user.jobs.new(job_params)
  	if @job.save
  		flash[:success] = "Thanks for submitting your job! Your listing should be live within the next 24 hours, and we'll drop you an email when it is."
  		redirect_to root_path
  	else
  		flash[:error] = "No. Try again."
  		render :new
  	end
  end

  def edit
    current_user_owns_job
    @job = Job.find(params[:id])
  end

  def update
    current_user_owns_job
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:success] = "All done"
      redirect_to root_path
    else
      flash[:error] = "Nope"
      render :new
    end
  end


  private

  def job_params
  	params.require(:job).permit(:title, :company, :company_url, :job_url, :job_email, :description, :approved, :area_of_london, :salary, :how_to_apply)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	@email = params[:session][:email]
  	@password = params[:session][:password]

  	@user = User.find_by(email: @email)

  	if @user.present? and @user.authenticate(@password)
  		flash[:success] = "Welcome back #{@user.name}"
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		flash[:error] = "Try again"
  		render :new  		
  	end
  end

  def destroy
  	reset_session
  	flash[:success] = "You have logged out"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Thanks for signing up!"
      session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		flash[:error] = "That didnt work"
  		render :new
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_active_class(name, active_class_names, options = {}, html_options = {}, &block)
	  html_options[:class] = html_options[:class].to_s + active_class_names if current_page?(options.to_s)
	  link_to name, options, html_options, &block
	end

	def markdown(text)
	    options = {
	      filter_html:     true,
	      hard_wrap:       true, 
	      link_attributes: { rel: 'nofollow', target: "_blank" },
	      space_after_headers: true, 
	      fenced_code_blocks: true
	    }

	    extensions = {
	      autolink:           true,
	      superscript:        true,
	      disable_indented_code_blocks: true
	    }

	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)

	    markdown.render(text).html_safe
	  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for [@user, @job] do |f| %>

	<%= f.input :title %>
	<%= f.input :company %>
	<%= f.input :company_url, :input_html => { :value => 'http://' } %>
	<%= f.input :job_url, :input_html => { :value => 'http://' } %>
	<%= f.input :job_email %>
	<%= f.input :description %>
	<em>This form accepts <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a>.</em>

	<div class="submit">
		<%= f.submit %>
	</div>

<% end %>

app/views/jobs/edit.html.erb
<div class="wrapper">
	
	<h1>Edit your job listing</h1>

	
	<%= simple_form_for [@user, @job] do |f| %>

		<%= f.input :title %>

		<%= f.input :company %>

		<%= f.input :area_of_london %>

		<%= f.input :company_url %>

		<%= f.input :job_email %>

		<%= f.input :description %>
		<p>This field accepts <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> (and so does the next one).</p>

		<%= f.input :how_to_apply %>

		<%= f.input :job_url %>

		<%= f.input :salary %>

		<div class="submit">
			<%= f.submit %>
		</div>

	<% end %>
</div>

app/views/jobs/index.html.erb
<div class="wrapper">
	<h2>Latest jobs</h2>

	<ul id="jobs-list">

	<% @jobs.each do |job| %>

		<li>
			<%= link_to job_path(job) do %>
				<%= job.title %><span> at <%= job.company %></span> 

			<% end %>
			<small><%= time_ago_in_words job.created_at %> ago</small>
		</li>

	<% end %>

	</ul>
</div>

app/views/jobs/new.html.erb
<div class="wrapper">
	
	<h1>Post a job</h1>

	<div class="desc">
		<p>For a limited time, posting a job on here will be free. It's as simple as filling out this form. We'll then check it through and get it live within 24 hours.</p>
	</div>

	
	
	<%= simple_form_for [@user, @job] do |f| %>

		<%= f.input :title %>
		<p>Eg. 'Junior Designer' or 'UX designer'</p>

		<%= f.input :company %>
		<p>Name of the company</p>

		<%= f.input :area_of_london %>
		<p>Where the position is based</p>

		<%= f.input :company_url %>
		<p>Include 'http://'</p>

		<%= f.input :job_email %>
		<p>If you'd like candidates to email applications, enter your email here</p>

		<%= f.input :description %>
		<p>This field accepts <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> (and so does the next one). Be as descriptive as you can be</p>

		<%= f.input :how_to_apply %>
		<p>Specify how candidates should apply for the position e.g. Email with CV and portfolio or complete a Google Form etc</p>

		<%= f.input :job_url %>
		<p>If your job is advertised on your own website too, enter the URL here</p>

		<%= f.input :salary %>
		<p>Eg. 300 per day, or 20,000 pa</p>

		<div class="submit">
			<%= f.submit %>
		</div>

	<% end %>
</div>

app/views/jobs/show.html.erb
<div class="back">
	<%= link_to "Back", root_path %>
</div>

<div class="wrapper">
	
	<div class="header">
		<h1><%= @job.title %></h1>
		<div class="meta">
			<p>at <%= link_to @job.company, "#{@job.company_url}", target: 'blank' %> - added <%= time_ago_in_words @job.created_at %> ago</p>
		</div>
	</div>

	<div class="desc">
		<p><%= markdown(@job.description) %></p>

		<h3>How to apply</h3>
		<p><%= markdown(@job.how_to_apply) %></p>
	</div>

	<div class="footer">

		<div>
			<p>Salary: £<%= @job.salary %></p>
			<p>Area: <%= @job.area_of_london %></p>
			<p>Added <%= time_ago_in_words @job.created_at %> ago</p>
		</div>
		<div>

			<% if @job.job_url? %>
				<p><%= link_to "More about the job", @job.job_url, target: 'blank' %> (on the company website)</p>
			<% end %>

			<% if @job.job_email? %>
			  <p>Email: <%= mail_to @job.job_email %></p>
			<% end %>

			<% if logged_in? and current_user == @job.user %>
				<p><%= link_to "Edit", edit_job_path(@job), class: 'button' %></p>
			<% end %>
		</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Design Jobs LDN</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//use.typekit.net/tuj6ivy.js"></script>
	<script>try{Typekit.load();}catch(e){}</script>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-55975085-1', 'auto');
	  ga('send', 'pageview');

	</script>

</head>
<body>

<header>
	
	<div id="logo">
			<%= link_to "London Design Jobs", root_path %>
	</div>

	<h1>A brand new site dedicated to design jobs in London</h1>

	<nav class="nav-collapse">
		<ul>
			<li><%= link_to_active_class "Jobs", "selected", root_path %></li>
			<li><%= link_to_active_class "Freelancers", "selected", '/freelance' %></li>
			<% if logged_in? %>
				<li><%= link_to_active_class "Post a job", "selected", new_user_job_path(current_user.id) %></li>
			<% else %>
				<li><%= link_to "Post a job", new_user_path %></li>
				<li class="small"><%= link_to "Log in", new_session_path %></li>
				<li class="small"><%= link_to "Sign up", new_user_path %></li>
			<% end %>
			<li class="small"><%= link_to "About", '/about' %></li>
			<% if logged_in? %>
				<li class="small"><%= link_to "Log out", session_path, method: :delete  %></li>
			<% end %>
			<li class="twitter"><a href="http://www.twitter.com/designjobsldn" target="_blank">Twitter</a></li>
		</ul>
	</nav>
	
	<script>
      var navigation = responsiveNav(".nav-collapse");
    </script>

	
</header>

<div id="content">
	<div class="wrapper">
		<% flash.each do |key, value| %>
			<div class="<%= key %>">
				<p><%= value %></p>
			</div>
		<% end %>
	</div>
	
	<%= yield %>

</div>

<div class="right">
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="wrapper">

	<div class="header">
		<h1>A place for designers in London</h1>
	</div>

	<div class="desc">
		<p>Design Jobs LDN is a jobs board specifically for designers in London. We want to become the place where designers find the job they’re after.</p>

		<h3>Our mission</h3>
		<p>There are plenty of jobs boards out there, but we are the first for designers in London only.</p>

		<h3>The cost</h3>
		<p>We believe listing a job shouldn't cost hundreds of pounds. We pride ourselves on being just £50 per post. And for a limited time, whilst we’re getting our name out there, you can post your job for FREE.</p> 

		<h3>Who we are</h3>
		<p>DJL was started by designers who have experience both searching for jobs, as well as hunting for new hires. We know that either side can be tough. We hope to make it easier for both.</p>

		<h3>Contact</h3>
		<p>Feel free to get in touch on <a href="mailto:hello@designjobsldn.com">hello@designjobsldn.com</a>, with any questions or comments.</p>

		<p><em>We are very new and continuing to develop the site. We apologise if anything breaks at any point. If anything seems to be very wrong, <a href="mailto:hello@designjobsldn.com">email us</a>, otherwise I'm sure we'll have it fixed pretty quick.</em></p>

	</div>


</div>

app/views/pages/freelance.html.erb
<div class="wrapper">
	
	<div class="header">
		<h1>London based freelancers</h1>
	</div>
	<div class="desc">
		<p>We're building a list of the best London based freelance designers. So, when you need a bit of extra help on your next project, you know where to come.</p>
		<p>Are you a freelance designer in London? Want to be on the list? Email us at <a href="mailto:hello@designjobsldn.com">hello@designjobsldn.com</a></p>
	</div>



</div>

app/views/pages/projects.html.erb
<div class="wrapper">
	
	<div class="header">
		<h1>Projects, coming soon</h1>
	</div>
	<div class="desc">
		<p>We're creating an amazing way for freelancers to search for and find projects. We'll be launching this real soon, so leave your email below if you'd like to stay informed.</p>
	</div>

	<!-- Begin MailChimp Signup Form -->
	<div id="mc_embed_signup">
	<form action="//designjobsldn.us9.list-manage.com/subscribe/post?u=9c300813c3098f02afdbaefb5&amp;id=e2c899a285" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	    <div id="mc_embed_signup_scroll">
	
	<div class="mc-field-group">
		<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
	</label>
		<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
	</div>
	<div class="mc-field-group">
		<label for="mce-FNAME">First Name </label>
		<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
	</div>
	<div class="mc-field-group">
		<label for="mce-LNAME">Last Name </label>
		<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
	</div>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;"><input type="text" name="b_9c300813c3098f02afdbaefb5_e2c899a285" tabindex="-1" value=""></div>
	    <div class="submit">
	    	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	    </div>
	    </div>
	</form>
	</div>

	<!--End mc_embed_signup-->

</div>

app/views/users/new.html.erb
<div class="wrapper">

	<div class="header">
		<h1>Welcome</h1>

		<h2>You need to create an account to post a job with us. <br/>Aleady got an account? 
		<%= link_to "Log in here", new_session_path %></h2>
	</div>

	<%= simple_form_for @user do |f| %>

		<%= f.input :name %>
		<%= f.input :username %>
		<%= f.input :email %>
		<%= f.input :password %>
		<%= f.input :password_confirmation %>

		<div class="submit">
			<%= f.button :submit, "Sign up" %>
		</div>

	<% end %>
</div>